import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    
    in-out property<int> counter: 42;
    callback request-increase-value();

    width: 400px;
    height: 140px;

    default-font-size: 16px;

    forward-focus: button;

    VerticalBox {
        alignment: space-between;
        padding: 20px;
        spacing: 20px;

        Text {
            text: "Counter: \{root.counter}";
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        button := Button {
            text: "Increase Value";
            primary: true;
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
